#! /bin/bash

  if [ ! -d /dev/gpio ]; then
  echo "Creating /dev/gpio"
  mkdir /dev/gpio
  fi
  
  if [ ! -f /dev/gpio/ ]; then
    ln -s /sys/class/gpio/gpio468/value /dev/gpio/QCS_WLAN_SW_CTRL
  fi
